### PR TITLE
Exposes the function to import CSVs of reciprocal relationships…

### PR DESCRIPTION
**Pull request by ckoppelman**
…so that other pacakage developers can use it.

This is a minor refactor to allow third-party developers to reuse the work of the NPSP

### CODE REVIEW

**Comment by davidhabib** [comment]
@ckoppelman thanks for the pull request.  I've created an issue in the Cumulus gitHub issues list to refer to this request, otherwise it will get missed by the team. https://github.com/SalesforceFoundation/Cumulus/issues/2161

Can you please annotate this issue with information about why you want this change and how it will be used?  thanks.

**Comment by ckoppelman** [comment]
If I should be targetting a different branch, do let me know.  `dev/` seems behind at the moment.

**Comment by judisohn** [comment]
Hi @ckoppelman - Thank you so much for this pull request. We all agree it's great and needed functionality but unfortunately we didn't have room to include in this sprint. We'll work on getting it in to our next sprint which begins in 2 weeks.

In the meantime, could you download and sign our [Contributor License Agreement](https://drive.google.com/file/d/0B03ZNgpt5Nn6OWI5bVRDd0pKZWs/view?usp=sharing) and [email back to me](mailto://jsohn@salesforce.com) as soon as is convenient? Thank you so much.

**Comment by ckoppelman** [comment]
Understood.  And sent.

Judi Sohn wrote:

**Comment by judisohn** [comment]
Hi @ckoppelman - at our Sprint planning session yesterday, the development team reviewed and discussed this pull request at length. The decision was made not to accept at this time. The current implementation of default relationship values is meant to provide a simple and universal starting point for reciprocal relationships. We don't see a strong enough need for this use case to justify implementing error handling, documentation, and providing ongoing maintenance and support for a global API to accomplish this within NPSP itself.

One-off implementations with the need for custom reciprocal relationships should import their own relationship values through the data loader; package developers such as yourself can provide their own post-install script to load their own defaults, including handling deletion of NPSP default reciprocal relationship values if desired. The onus is then on those developers to vet their implementation and CSV format without relying on NPSP's implementation.

Thank you so much for taking the time to submit this work to us, and we look forward to and encourage further contribution. Please feel free to reach out if you have any questions.

**Pull request closed without merging**
