### PR TITLE
Change Type__c label. Reorder page layout.

### PR DESCRIPTION
**Pull request by Zosoled**
Resolves SalesforceFoundation/Cumulus#1331

# Critical Changes

# Changes

# Issues Closed
- Fixes SalesforceFoundation/Cumulus#1331

### CODE REVIEW

**Comment by judisohn** [comment]
@Zosoled Awesome! Are you able to sign a CLA now? Send me an email at jsohn@salesforce.com and I'll send you a new one if so. FYI @coriobriensfdo - I just realized I never entered this as a Product Contribution, sorry about that!

Thanks again, Chris! Once we have a CLA we can work with our teams to get this in next time we have to make an update to this package.

**Comment by coriobriensfdo** [comment]
**lurch: attach W-008292

**Comment by coriobriensfdo** [comment]
Issue: https://github.com/SalesforceFoundation/Cumulus/issues/1331

**Comment by coriobriensfdo** [comment]
**lurch: attach W-008292

**Comment by Zosoled** [comment]
Absolutely, I’d be happy to. :) 

Chris
Sent from iPhone

On May 24, 2019, at 09:24, coriobriensfdo <notifications@github.com> wrote:

**lurch: attach W-008292

**Comment by coriobriensfdo** [comment]
@Zosoled any reason why you closed the PR?

**Comment by coriobriensfdo** [comment]
**Lurch: Attach W-008292

**Comment by Zosoled** [comment]
Nope that was in error. Thanks!

**Pull request closed without merging**
