### PR TITLE
Removing unused static resources.

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by njjc** [comment]
@cpolcyn Couple of questions for you:
We need to remove these static resources from this underlying package in order to pass security review. Do you know if static resources removed from a package need to be deleted by customers? If so, we'll need some release notes related to this change. I take it those will need to be included in a pull request on the Cumulus repo?

**Comment by cpolcyn** [comment]
I believe it would be removed automatically like any other deleted component, but not sure. @jlantz any idea?

**Comment by njjc** [comment]
It's just marked as available for deletion per [this documentation](https://developer.salesforce.com/docs/atlas.en-us.packagingGuide.meta/packagingGuide/packaging_packageable_components.htm). So we do need release notes telling users they can remove these static resources. Would that have to be in a Cumulus PR or can I just include the release notes here? @cpolcyn

**Comment by cpolcyn** [comment]
Good catch, they would not be deleted for the subscriber on upgrade. As for the notes, please add to the relevant PR.

**Comment by njjc** [comment]
So... this is the relevant PR, but it's part of an underlying package. Will these get rolled up to the Cumulus package release notes? @cpolcyn

**Comment by cpolcyn** [comment]
Ah gotcha, usually we would also put something in a Cumulus PR but I'm not sure if there's a related one that was merged. I can just merge the release notes when posting in the Hub.

**Comment by njjc** [comment]
@smarovich I'd love some help with release notes for this PR; we're removing unused static resources that can be deleted by customers once this release is out. Ping me when you have a moment, please!

**Comment by smarovich** [comment]
@njjc I realized I never wrote release notes for your PR, so I just added some. They're very similar to what I wrote for Kofi's PR. If you need or want to make changes, feel free. Jon or Liane can help if you need some doc wordsmithing. If this PR goes into the 1/3 release, Jon is assigned the article referenced in the release notes, so he can publish it.

**Pull request merged**
