### PR TITLE
Change Type__c label. Reorder page layout.

### PR DESCRIPTION
**Pull request by Zosoled**
Resolves SalesforceFoundation/Cumulus#1331

### CODE REVIEW

**Comment by judisohn** [comment]
@Zosoled why did you close it?

**Comment by Zosoled** [comment]
I've been asked to hold contributions by my employer. I haven't yet signed the CLA for this reason as well, so I didn't want this pull request to get merged without that being in place. I'll be more than happy to re-open this later.

**Comment by judisohn** [comment]
Understood - if there are questions about the CLA, please feel free to have someone reach out to me.

**Comment by Zosoled** [comment]
Will do. Thanks!

**Pull request closed without merging**
